import "./globals.css";
import Navbar from "../components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        <main className="relative overflow-x-hidden dark:bg-dark">
          {children}
        </main>
        </body>
    </html>
  );
}
